# @package model
defaults:
  - _base

name: splade_v2_pp_embeddinggemma_300m_pruned
huggingface_name: ${root_dir_path}/data/model/trained_embeddinggemma_300m_pruned
huggingface_model_class: AutoModelForCausalLM
trust_remote_code: false
use_fast_tokenizer: true
require_fast_tokenizer: true
query_pooling: max
doc_pooling: max
sparse_activation: log1p_relu
