name: SPLADE
services:
    SPLADE:
        image: hyukkyukang/splade:latest
        container_name: SPLADE

        shm_size: 128gb
        ulimits:
            memlock: -1
        stdin_open: true
        tty: true
        user: user
        network_mode: "host"

        environment:
            - TZ=Asia/Seoul
            - HOST_UID=${UID}
            - HOST_GID=${GID}
            - SSL_CERT_FILE=/home/user/.local/share/ca-certificates/combined-ca-bundle.crt
            - CURL_CA_BUNDLE=/home/user/.local/share/ca-certificates/combined-ca-bundle.crt
            - REQUESTS_CA_BUNDLE=/home/user/.local/share/ca-certificates/combined-ca-bundle.crt
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /home/hyukkyukang/SPLADE:/home/user/SPLADE
            - /mnt/ex-disk-1/hyukkyukang:/mnt/ex-disk-1/hyukkyukang/
            - ${HOME}/.local/share/ca-certificates:/host-ca-certificates:ro
        working_dir: /home/user/SPLADE
        command: /bin/bash /home/user/SPLADE/docker/container-init.sh
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
