# @package training
defaults:
  - _base

name: splade_v2_pp

torch_compile: true
torch_compile_loss: true
batch_size: 32
eval_batch_size: 8
grad_accumulation: 1
static_graph: true
find_unused_parameters: false

regularization:
  query_weight: 0.0002
  doc_weight: 0.0001
  type: flops
  paper_faithful: true
  schedule_steps: 50000
