# @package training
defaults:
  - _base

name: splade_v2_anna_large

batch_size: 16
grad_accumulation: 2
# Turn off to avoid PyTorch DDP runtime bug 
static_graph: false
# lr: 1e-5
temperature: 10.0

regularization:
  query_weight: 0.0002
  doc_weight: 0.0001
  type: flops
  paper_faithful: true
  schedule_steps: 50000
