# @package encoding
name: encoding_base

batch_size: 1024
num_workers: 10
prefetch_factor: 4
max_padding: true

precision: bf16-mixed
torch_compile: true
torch_compile_mode: default
use_cpu: false
strategy: ddp
static_graph: true
num_devices: null

checkpoint_path: null

encode_dir: "log/encode"
index_dir: "log/index"
index_tag: ${tag}

shard_max_docs: 100000
value_dtype: float32
sparse_min_weight: 0.0
sparse_top_k: 512
wand_block_size: 256

async_write: true
async_write_queue_size: 8