# @package dataset
defaults:
  - _base@_here_

name: patent_us_corpus_small
type: corpus_only
split: train
corpus_split: train
hf_split: train

max_doc_length: 512

query_corpus_hf_name: parquet
query_corpus_hf_data_files:
  train: .cache/hf/patent-us-corpus-small/data/*.parquet
query_subset_name: null
corpus_subset_name: null

query_id_column: doc_id
query_text_column: abstract
corpus_id_column: doc_id
corpus_title_column: title
corpus_text_column: abstract
corpus_additional_text_columns:
  - claims
  - description
corpus_text_template: patent_document_v1
